### ISSUE TITLE
'Quick Documentation' action does not work with "//" comments

### ISSUE THREAD

**Issue by kool79** [AVSystem/intellij-hocon#22]
> Version 2019.3.2: What’s New
> 'Quick Documentation' action for displaying documentation of HOCON entries

This works only for comments statred with `#` but does not work for `//`-comments. 
Is it expected?
![Screenshot - 15_10_2019 , 17_52_03](https://user-images.githubusercontent.com/4625317/66842870-a3829680-ef74-11e9-9d9f-edae111906ba.png)

**Comment by ghik** [comment]
Yes, this is intended.

HOCON itself doesn't have a concept of "documentation comments" so I arbitrarily decided to treat `#` as "documentation comment" and left `//` as "plain comment". This matches the convention used in Akka reference files. It also gives the user the ability to decide whether a comment should be interpreted as documentation or not.

**Comment by kool79** [comment]
ok. will close the issue. But will be good to have documentation or some example on plugin page or here in README. I never worked with Akka so it was not obvious for me.
