### ISSUE TITLE
FileNotFoundException during sbt compile

### ISSUE THREAD

**Issue by jirislav** [AVSystem/intellij-hocon#30]
Hi,

I'm trying to compile (using `sbt compile`) the plugin in IntelliJ, but with no success, the console states:
```
java -Xmx512M -Dsbt.log.noformat=true -jar /home/jirislav/.cache/JetBrains/IdeaIC2020.2/sbtexe/sbt-launch-1.3.9.jar compile exit
[info] Loading global plugins from /home/jirislav/.sbt/1.0/plugins
[info] Loading settings for project hocon-intellij-build from plugins.sbt ...
[info] Loading project definition from /opt/hocon-intellij/project
[info] Loading settings for project hocon from build.sbt ...
[info] Set current project to hocon (in build file:/opt/hocon-intellij/)
[info] Resolving ideaIC dependency for BuildInfo(193.4778.7,org.jetbrains.sbtidea.Defns$IntelliJPlatform$IdeaCommunity$@4fdfd9cd)
Can't find BuildInfo(193.4778.7,org.jetbrains.sbtidea.Defns$IntelliJPlatform$IdeaCommunity$@4fdfd9cd) in releases, trying snapshots
[error] java.io.FileNotFoundException: https://d2s4y8xcwt8bet.cloudfront.net/com/jetbrains/intellij/idea/ideaIC/193.4778.7-EAP-SNAPSHOT/ideaIC-193.4778.7-EAP-SNAPSHOT.zip
```
- no matter what version of the plugin I checkout

Do you have any hint as what I might be doing wrong? I simply created new project from existing sources and checked that it's a sbt project.

Thanks.

**Comment by ghik** [comment]
Hi, do you specifically need to work with IDEA 193.x?

In any case, please try updating IDEA build version in `build.sbt` (`intellijBuild in ThisBuild := ...`) to some newer build. You can look them up here: https://confluence.jetbrains.com/display/IDEADEV/Latest+builds
I haven't updated the plugin for quite a while and the old IDEA build that's currently configured in `build.sbt` is probably no longer available in JetBrains repositories.

**Comment by jirislav** [comment]
No I don't need 193.x, but as I said, I get the same error message for any version of IDEA (I also tried 201.x and the latest 202.7660.26, also no luck).

**Comment by ghik** [comment]
Ok then: IDEA builds are downloaded by [sbt-idea-plugin](https://github.com/JetBrains/sbt-idea-plugin) which probably needs to be updated.

**Comment by jirislav** [comment]
Thank you, upgrading that plugin helped!

```diff
diff --git a/build.sbt b/build.sbt
index c997b11..2a29f04 100644
--- a/build.sbt
+++ b/build.sbt
@@ -1,7 +1,7 @@
 import org.jetbrains.sbtidea.Keys._
 
 intellijPluginName in ThisBuild := "intellij-hocon"
-intellijBuild in ThisBuild := "201.5616.10"
+intellijBuild in ThisBuild := "202.7660.26"
 
 val junitInterfaceVersion = "0.11"
 val silencerVersion = "1.6.0"
diff --git a/project/plugins.sbt b/project/plugins.sbt
index 94d2a8c..a4ef661 100644
--- a/project/plugins.sbt
+++ b/project/plugins.sbt
@@ -1,4 +1,4 @@
 resolvers += Resolver.url("jetbrains-sbt", url(s"https://dl.bintray.com/jetbrains/sbt-plugins"))(Resolver.ivyStylePatterns)
 
-addSbtPlugin("org.jetbrains" % "sbt-idea-plugin" % "3.5.0")
+addSbtPlugin("org.jetbrains" % "sbt-idea-plugin" % "3.7.5")
 addSbtPlugin("org.jetbrains" % "sbt-ide-settings" % "1.0.0")
```
