### ISSUE TITLE
Folding not working

### ISSUE THREAD

**Issue by NealRM** [AVSystem/intellij-hocon#33]
Apache conf file on Ubuntu

Folding is not working.

**Comment by ghik** [comment]
Hello @NealRM,

"Folding is not working" is not an appropriate issue description. You need to provide at least some minimal reproduction information, for example contents of the configuration file.

I don't know what an "Apache conf file on Ubuntu" exactly is. Is this a system configuration file? As far as I know, Ubuntu config files don't use HOCON. It's unfortunate that the `.conf` file extension is used by various configuration formats.
