### ISSUE TITLE
Navigation to definition not working when using classpath file

### ISSUE THREAD

**Issue by swaraj2204** [AVSystem/intellij-hocon#35]
I am using Spark in HOCON and in HDInsight I have to use following configuration

`include required(classpath("test/base/base-conf.conf"))` 

This resides in "src/main/resources/test/base"

I have a file in the directory called "src/main/resources/test/derived" and in this file the navigation is not working.

**Comment by ghik** [comment]
Hi @swaraj2204 do you mean something like this?
![obraz](https://user-images.githubusercontent.com/1022675/119399625-68f8e800-bcd9-11eb-9cdb-96e5fc4b54a7.png)

This seems to be working fine for me.
If it still doesn't work for you, please provide some minimal project that demonstrates this bug.

**Comment by swaraj2204** [comment]
I got this working now. I was having 2019.1 version in my IDE where the changes came after 2019.3.3. Thanks for your reply.
