### ISSUE TITLE
please add a plugin for new IDEA 2023.1 that is now in the EAP stage

### ISSUE THREAD

**Issue by kseniaxnx** [AVSystem/intellij-hocon#41]
please add a plugin support for new IDEA 2023.1 that is now in the EAP stage
https://www.jetbrains.com/idea/nextversion

**Comment by nafg** [comment]
Does it actually need changes or just a metadata update?

**Comment by ghik** [comment]
Hi, I will look into it. Some APIs in IntelliJ used by the plugin may have been depracated, which may require changes.

**Comment by ghik** [comment]
2023.1.0 is released. Enjoy.
