### ISSUE TITLE
Compatible with nginx. conf

### ISSUE THREAD

**Issue by laglangyue** [AVSystem/intellij-hocon#42]
The conf file is recognized as hocon, but nginx. conf will generate many errors. Is it compatible with nginx. conf

**Comment by ddworak** [comment]
No, the plugin is not intended to support any other conf files than HOCON. As mentioned in the README:
```
Files with *.conf extensions are automatically interpreted as HOCON files. 
Because *.conf is a common extension, you can change this in File -> Settings -> Editor -> File Types.
```
Please reconfigure the file types according to the needs of your project. The plugin cannot make any other expectation about the file pattern to avoid this inconvenience.
