### ISSUE TITLE
Support for 2024.2 EAP?

### ISSUE THREAD

**Issue by PagerTreadmillAttic** [AVSystem/intellij-hocon#47]
IDEA's early access version 2024.2 is out and it's reporting that this plugin is "marked as incompatible". I can't tell if this is a code problem or some missing metadata.

It looks like #43 was mostly metadata, hopefully support for 2024.2 will be just as easy?

**Comment by ddworak** [comment]
@PagerTreadmillAttic no way to know until we try ;) We'll find someone to take a look soon, unless you want to try locally and contribute?

**Comment by PagerTreadmillAttic** [comment]
I've already checked out the source, but I don't know Scala or IntelliJ plugin development, so I'm not sure when I'll be able to do it myself. If I can find the time to figure it out, I'll open a PR!
